version: '3'

services:
  app:
    container_name: django
    build: ./django
    volumes:
     - ./django/code/:/code
    ports:
     - 8000:8000
    command: python mysite/manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: mysql
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3333:3306
    expose:
      - 3333
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    # privileged: true
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s