version: '3.8'

services:
  app:
    container_name: django
    build: ./django
    volumes:
     - ./django:/django
    ports:
     - 58080:8000
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      dynamodb:
        condition: service_started

  db:
    container_name: mysql
    image: mysql:8.4.2
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dynamodb:
    container_name: example-dynamodb
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    ports:
      - 50706:8000

  dynamodb-admin:
    container_name: example-dynamodb-admin
    build: ./dynamodb-admin/
    command: ["dynamodb-admin", "-p", "8000"]
    env_file: ./dynamodb-admin/.env
    environment: 
      DYNAMO_ENDPOINT: http://example-dynamodb:8000
    ports:
      - 50727:8000
    depends_on:
      - dynamodb

  minio:
    image: minio/minio:RELEASE.2022-10-08T20-11-00Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/export