version: '3.8'

services:
  app:
    container_name: django
    build: ./django
    volumes:
     - ./django/code/:/code
    ports:
     - 58080:8000
    command: python mysite/manage.py runserver 0.0.0.0:8000
    depends_on:
      db:
        condition: service_healthy
      dynamodb:
        condition: service_started

  db:
    container_name: mysql
    build: ./mysql
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3333:3306
    environment:
      TZ: 'Asia/Tokyo'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 'django'
      MYSQL_USER: 'django'
      MYSQL_PASSWORD: 'django'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  dynamodb:
    container_name: example-dynamodb
    image: amazon/dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/home/dynamodblocal/data"]
    volumes:
      - ./persist/dynamodb:/home/dynamodblocal/data
    ports:
      - 50706:8000

  dynamodb-admin:
    container_name: example-dynamodb-admin
    build: ./dynamodb-admin/
    command: ["dynamodb-admin", "-p", "8000"]
    env_file: ./dynamodb-admin/.env
    environment: 
      DYNAMO_ENDPOINT: http://example-dynamodb:8000
    ports:
      - 50727:8000
    depends_on:
      - dynamodb
